### ISSUE TITLE
microsecond timing

### ISSUE THREAD

**Issue by jpillora** [jpillora/go433#2]
@davecheney Hey Dave, do you any experience with microsecond timing, Go and an rpi2?

This C++ library ([RCSwitch](https://github.com/sui77/rc-switch/blob/master/RCSwitch.cpp)) compiles and works. In short, it [encodes messages](https://github.com/jpillora/go433/blob/master/rc_switch.go#L470-L473) as:

```
1 is: 3 high and 1 low
_ _ _
     |_
0 is: 1 high and 3 low
_
 |_ _ _
```

ending with 1 high and 31 low, where each high and low pulse has a pulse width of **350us**

I'm attempting to replicate just the send functionality [here](https://github.com/jpillora/go433/blob/master/cmd/go433send/go433send.go) using your gpio library to no avail.

Do you know if Go has issues with timings this accurate?

**Comment by davecheney** [comment]
You won't be able to get that kind of timing using the /proc interface.
You'll have to use the version that talks directly to the hardware via
/dev/kmem

I wrote several GPIO packages, but tbh I haven't looked at them in a few
years.

**Comment by jpillora** [comment]
Ah okay, thanks. Will look into it

**Comment by davecheney** [comment]
This version uses the fast method on the RPi1, I haven't tested it on the
RPi2.

https://github.com/davecheney/gpio/tree/master/rpi

No warranty, express or implied.

**Comment by jpillora** [comment]
Just tested it, no go. Will look around, if I don't find anything, will resort to wiringPi bindings. Thanks again

**Comment by jpillora** [comment]
Hey Dave, just incase you were interested – I found a library (https://github.com/stianeikeland/go-rpio) that writes to `/dev/gpiomem` and it seems to work now :) Not as reliably as the C++ version though so I'll just send repeat transmissions to ensure it makes it
